## Handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

In [1]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0, n_class_1

(900, 100)

In [3]:
## CREATE MY DATAFRAME WITH IMBALANCED DATASET
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [4]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [6]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [7]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## UP Sampling

In [9]:
# upsampling
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [17]:
from sklearn.utils import resample
df_minority_upsampled = resample(df_minority, 
                              replace=True,  # sample with replacement  
                              n_samples=len(df_majority),  # to match majority class  
                              random_state=123)  # reproducible results

In [18]:
df_minority_upsampled.shape

(900, 3)

In [19]:
df_minority_upsampled.head()

     feature_1  feature_2  target
966   0.671933   1.370988       1
992   2.196570   1.397425       1
998   2.902006   0.390305       1
917   2.197269   4.216788       1
983   2.844335   2.015572       1

In [23]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [24]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sampling

In [26]:
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

# Check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [27]:
# downsampling
df_majority = df[df['target'] == 0]
df_minority = df[df['target'] == 1]

In [30]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority,
                                   replace=False,  # sample without replacement
                                   n_samples=len(df_minority),  # to match minority class            
                                   random_state=123)  # reproducible results

In [31]:
df_majority_downsampled.shape

(100, 3)

In [33]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [34]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64