## Support Vector Regression

In [26]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [27]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [29]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [30]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [31]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [32]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [33]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [34]:
X = df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y = df['total_bill']

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((195, 6), (49, 6), (195,), (49,))

In [36]:
X_train.head()

      tip   sex smoker   day    time  size
228  2.72  Male     No   Sat  Dinner     2
208  2.03  Male    Yes   Sat  Dinner     2
96   4.00  Male    Yes   Fri  Dinner     2
167  4.50  Male     No   Sun  Dinner     4
84   2.03  Male     No  Thur   Lunch     2

In [37]:
y_train.head()

228    13.28
208    24.27
96     27.28
167    31.71
84     15.98
Name: total_bill, dtype: float64

In [38]:
# Feature Encoding(LAbel Encoding And Onehot Encoding)
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [39]:
X_train['sex'] = X_train['sex'].str.strip()
X_test['sex'] = X_test['sex'].str.strip()

X_train['smoker'] = X_train['smoker'].str.strip()
X_test['smoker'] = X_test['smoker'].str.strip()

X_train['time'] = X_train['time'].str.strip()
X_test['time'] = X_test['time'].str.strip()

In [40]:
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])
X_train['time'] = le3.fit_transform(X_train['time'])

In [41]:
X_train.head()

      tip  sex  smoker   day  time  size
228  2.72    1       0   Sat     0     2
208  2.03    1       1   Sat     0     2
96   4.00    1       1   Fri     0     2
167  4.50    1       0   Sun     0     4
84   2.03    1       0  Thur     1     2

In [42]:
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['time'] = le3.transform(X_test['time'])

In [43]:
X_test.head()

      tip  sex  smoker   day  time  size
24   3.18    1       0   Sat     0     2
6    2.00    1       0   Sun     0     2
153  2.00    1       0   Sun     0     4
211  5.16    1       1   Sat     0     4
198  2.00    0       1  Thur     1     2

In [44]:
# Onehot encoding--- ColumnTrnasformer

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(drop='first'), [3])], remainder='passthrough')

In [45]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)

In [46]:
X_test = ct.transform(X_test)

In [47]:
X_test

array([[1.  , 0.  , 0.  , 3.18, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 5.16, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.56, 1.  , 1.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 2.52, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.23, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 3.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.  , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.47, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.5 , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.83, 0.  , 0.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.36, 0.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 1.  , 4.  , 1.  , 1.  , 1.  , 3.  ],
       [0.  , 1.  , 0.  , 3.92, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.47, 0.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 1.  , 0.  , 1.  , 5.  ],
       [1.  , 0.  , 0.  , 2.45, 0.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.35, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 4.  , 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.45, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 1.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.31, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 1.71, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 5.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 5.  , 1.  , 0.  , 0.  , 6.  ],
       [0.  , 1.  , 0.  , 4.  , 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 1.44, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.34, 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.21, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.92, 0.  , 0.  , 1.  , 4.  ],
       [0.  , 0.  , 0.  , 1.5 , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 0.  , 1.  , 1.  , 4.  ],
       [0.  , 0.  , 1.  , 2.75, 0.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.25, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.55, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.67, 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  , 1.61, 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.31, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 1.44, 1.  , 0.  , 1.  , 2.  ]])

In [48]:
# SVR--Support Vector Regression
from sklearn.svm import SVR
svr = SVR()
svr.fit(X_train, y_train)

SVR()

In [49]:
y_pred = svr.predict(X_test)
y_pred

array([17.56181868, 14.42884138, 19.67019972, 28.37904435, 14.0459103 ,
       15.15208312, 15.62063514, 14.75174275, 17.79947653, 17.12672276,
       17.05846803, 13.23966396, 12.77479972, 15.15208312, 12.77679673,
       14.57988045, 22.32224518, 20.11534818, 15.27233318, 28.0803288 ,
       20.57815144, 20.70121756, 20.73942981, 13.21698051, 21.46941989,
       14.44332781, 13.92847397, 23.6918362 , 19.67019972, 28.39131072,
       22.94995085, 13.92076565, 20.30800717, 18.18328238, 21.149555  ,
       21.12511733, 13.83001582, 26.76204892, 15.40982357, 14.81618686,
       13.03210641, 13.52845761, 15.72878703, 15.85992199, 14.36572715,
       13.10808657, 14.02362016, 17.2075578 , 12.95474618])

In [50]:
from sklearn.metrics import r2_score,mean_absolute_error
print('R2 Score :', r2_score(y_test, y_pred))
print('MAE :', mean_absolute_error(y_test, y_pred))

R2 Score : 0.5502250005312896
MAE : 4.413774883497758

In [53]:
# Hyperparameter Tuning using GridSearch CV
from sklearn.model_selection import GridSearchCV
parameters = {
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'C': [0.1, 1, 10, 100],
    'gamma': ['scale', 'auto']}
grid_search = GridSearchCV(SVR(), parameters, refit = True, verbose = 3)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
[CV 1/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.381 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.487 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.525 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.260 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.284 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.586 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.355 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.570 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.208 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.002 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.096 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.080 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.085 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.044 total time=   0.0s
[CV 1/5] END C=0.1, gamma=scale, kernel=sigmoid;, score=-0.232 total time=   0.0s
[CV 2/5] END C=0.1, gamma=scale, kernel=sigmoid;, score=-0.095 total time=   0.0s
[CV 3/5] END C=0.1, gamma=scale, kernel=sigmoid;, score=-0.101 total time=   0.0s
[CV 4/5] END C=0.1, gamma=scale, kernel=sigmoid;, score=-0.096 total time=   0.0s
[CV 5/5] END C=0.1, gamma=scale, kernel=sigmoid;, score=-0.129 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.381 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.487 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.525 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.260 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.336 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.580 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.316 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.576 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.239 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=auto, kernel=rbf;, score=0.010 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=auto, kernel=rbf;, score=0.095 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=auto, kernel=rbf;, score=0.078 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=auto, kernel=rbf;, score=0.076 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=auto, kernel=rbf;, score=0.050 total time=   0.0s
[CV 1/5] END C=0.1, gamma=auto, kernel=sigmoid;, score=-0.231 total time=   0.0s
[CV 2/5] END C=0.1, gamma=auto, kernel=sigmoid;, score=-0.085 total time=   0.0s
[CV 3/5] END C=0.1, gamma=auto, kernel=sigmoid;, score=-0.097 total time=   0.0s
[CV 4/5] END C=0.1, gamma=auto, kernel=sigmoid;, score=-0.085 total time=   0.0s
[CV 5/5] END C=0.1, gamma=auto, kernel=sigmoid;, score=-0.136 total time=   0.0s
[CV 1/5] END ...C=1, gamma=scale, kernel=linear;, score=0.458 total time=   0.0s
[CV 2/5] END ...C=1, gamma=scale, kernel=linear;, score=0.664 total time=   0.0s
[CV 3/5] END ...C=1, gamma=scale, kernel=linear;, score=0.500 total time=   0.0s
[CV 4/5] END ...C=1, gamma=scale, kernel=linear;, score=0.572 total time=   0.0s
[CV 5/5] END ...C=1, gamma=scale, kernel=linear;, score=0.272 total time=   0.0s
[CV 1/5] END .....C=1, gamma=scale, kernel=poly;, score=0.382 total time=   0.0s
[CV 2/5] END .....C=1, gamma=scale, kernel=poly;, score=0.567 total time=   0.0s
[CV 3/5] END .....C=1, gamma=scale, kernel=poly;, score=0.284 total time=   0.0s
[CV 4/5] END .....C=1, gamma=scale, kernel=poly;, score=0.580 total time=   0.0s
[CV 5/5] END .....C=1, gamma=scale, kernel=poly;, score=0.266 total time=   0.0s
[CV 1/5] END ......C=1, gamma=scale, kernel=rbf;, score=0.376 total time=   0.0s
[CV 2/5] END ......C=1, gamma=scale, kernel=rbf;, score=0.465 total time=   0.0s
[CV 3/5] END ......C=1, gamma=scale, kernel=rbf;, score=0.442 total time=   0.0s
[CV 4/5] END ......C=1, gamma=scale, kernel=rbf;, score=0.377 total time=   0.0s
[CV 5/5] END ......C=1, gamma=scale, kernel=rbf;, score=0.269 total time=   0.0s
[CV 1/5] END .C=1, gamma=scale, kernel=sigmoid;, score=-0.882 total time=   0.0s
[CV 2/5] END .C=1, gamma=scale, kernel=sigmoid;, score=-0.751 total time=   0.0s
[CV 3/5] END .C=1, gamma=scale, kernel=sigmoid;, score=-0.608 total time=   0.0s
[CV 4/5] END .C=1, gamma=scale, kernel=sigmoid;, score=-0.604 total time=   0.0s
[CV 5/5] END .C=1, gamma=scale, kernel=sigmoid;, score=-0.493 total time=   0.0s
[CV 1/5] END ....C=1, gamma=auto, kernel=linear;, score=0.458 total time=   0.0s
[CV 2/5] END ....C=1, gamma=auto, kernel=linear;, score=0.664 total time=   0.0s
[CV 3/5] END ....C=1, gamma=auto, kernel=linear;, score=0.500 total time=   0.0s
[CV 4/5] END ....C=1, gamma=auto, kernel=linear;, score=0.572 total time=   0.0s
[CV 5/5] END ....C=1, gamma=auto, kernel=linear;, score=0.272 total time=   0.0s
[CV 1/5] END ......C=1, gamma=auto, kernel=poly;, score=0.433 total time=   0.0s
[CV 2/5] END ......C=1, gamma=auto, kernel=poly;, score=0.508 total time=   0.0s
[CV 3/5] END ......C=1, gamma=auto, kernel=poly;, score=0.238 total time=   0.0s
[CV 4/5] END ......C=1, gamma=auto, kernel=poly;, score=0.585 total time=   0.0s
[CV 5/5] END ......C=1, gamma=auto, kernel=poly;, score=0.307 total time=   0.0s
[CV 1/5] END .......C=1, gamma=auto, kernel=rbf;, score=0.400 total time=   0.0s
[CV 2/5] END .......C=1, gamma=auto, kernel=rbf;, score=0.445 total time=   0.0s
[CV 3/5] END .......C=1, gamma=auto, kernel=rbf;, score=0.438 total time=   0.0s
[CV 4/5] END .......C=1, gamma=auto, kernel=rbf;, score=0.341 total time=   0.0s
[CV 5/5] END .......C=1, gamma=auto, kernel=rbf;, score=0.274 total time=   0.0s
[CV 1/5] END ..C=1, gamma=auto, kernel=sigmoid;, score=-0.917 total time=   0.0s
[CV 2/5] END ..C=1, gamma=auto, kernel=sigmoid;, score=-0.698 total time=   0.0s
[CV 3/5] END ..C=1, gamma=auto, kernel=sigmoid;, score=-0.596 total time=   0.0s
[CV 4/5] END ..C=1, gamma=auto, kernel=sigmoid;, score=-0.561 total time=   0.0s
[CV 5/5] END ..C=1, gamma=auto, kernel=sigmoid;, score=-0.660 total time=   0.0s
[CV 1/5] END ..C=10, gamma=scale, kernel=linear;, score=0.509 total time=   0.0s
[CV 2/5] END ..C=10, gamma=scale, kernel=linear;, score=0.667 total time=   0.0s
[CV 3/5] END ..C=10, gamma=scale, kernel=linear;, score=0.508 total time=   0.0s
[CV 4/5] END ..C=10, gamma=scale, kernel=linear;, score=0.580 total time=   0.0s
[CV 5/5] END ..C=10, gamma=scale, kernel=linear;, score=0.254 total time=   0.0s
[CV 1/5] END ....C=10, gamma=scale, kernel=poly;, score=0.446 total time=   0.0s
[CV 2/5] END ....C=10, gamma=scale, kernel=poly;, score=0.474 total time=   0.0s
[CV 3/5] END ....C=10, gamma=scale, kernel=poly;, score=0.232 total time=   0.0s
[CV 4/5] END ....C=10, gamma=scale, kernel=poly;, score=0.584 total time=   0.0s
[CV 5/5] END ....C=10, gamma=scale, kernel=poly;, score=0.312 total time=   0.0s
[CV 1/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.519 total time=   0.0s
[CV 2/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.624 total time=   0.0s
[CV 3/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.535 total time=   0.0s
[CV 4/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.519 total time=   0.0s
[CV 5/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.298 total time=   0.0s
[CV 1/5] END C=10, gamma=scale, kernel=sigmoid;, score=-27.830 total time=   0.0s
[CV 2/5] END C=10, gamma=scale, kernel=sigmoid;, score=-26.723 total time=   0.0s
[CV 3/5] END C=10, gamma=scale, kernel=sigmoid;, score=-21.115 total time=   0.0s
[CV 4/5] END C=10, gamma=scale, kernel=sigmoid;, score=-18.662 total time=   0.0s
[CV 5/5] END C=10, gamma=scale, kernel=sigmoid;, score=-15.562 total time=   0.0s
[CV 1/5] END ...C=10, gamma=auto, kernel=linear;, score=0.509 total time=   0.0s
[CV 2/5] END ...C=10, gamma=auto, kernel=linear;, score=0.667 total time=   0.0s
[CV 3/5] END ...C=10, gamma=auto, kernel=linear;, score=0.508 total time=   0.0s
[CV 4/5] END ...C=10, gamma=auto, kernel=linear;, score=0.580 total time=   0.0s
[CV 5/5] END ...C=10, gamma=auto, kernel=linear;, score=0.254 total time=   0.0s
[CV 1/5] END .....C=10, gamma=auto, kernel=poly;, score=0.344 total time=   0.0s
[CV 2/5] END .....C=10, gamma=auto, kernel=poly;, score=0.368 total time=   0.0s
[CV 3/5] END .....C=10, gamma=auto, kernel=poly;, score=0.155 total time=   0.0s
[CV 4/5] END .....C=10, gamma=auto, kernel=poly;, score=0.526 total time=   0.0s
[CV 5/5] END .....C=10, gamma=auto, kernel=poly;, score=0.230 total time=   0.0s
[CV 1/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.497 total time=   0.0s
[CV 2/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.612 total time=   0.0s
[CV 3/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.574 total time=   0.0s
[CV 4/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.482 total time=   0.0s
[CV 5/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.324 total time=   0.0s
[CV 1/5] END C=10, gamma=auto, kernel=sigmoid;, score=-30.820 total time=   0.0s
[CV 2/5] END C=10, gamma=auto, kernel=sigmoid;, score=-23.973 total time=   0.0s
[CV 3/5] END C=10, gamma=auto, kernel=sigmoid;, score=-19.112 total time=   0.0s
[CV 4/5] END C=10, gamma=auto, kernel=sigmoid;, score=-20.329 total time=   0.0s
[CV 5/5] END C=10, gamma=auto, kernel=sigmoid;, score=-25.170 total time=   0.0s
[CV 1/5] END .C=100, gamma=scale, kernel=linear;, score=0.505 total time=   0.0s
[CV 2/5] END .C=100, gamma=scale, kernel=linear;, score=0.665 total time=   0.0s
[CV 3/5] END .C=100, gamma=scale, kernel=linear;, score=0.514 total time=   0.0s
[CV 4/5] END .C=100, gamma=scale, kernel=linear;, score=0.581 total time=   0.0s
[CV 5/5] END .C=100, gamma=scale, kernel=linear;, score=0.263 total time=   0.0s
[CV 1/5] END ...C=100, gamma=scale, kernel=poly;, score=0.289 total time=   0.0s
[CV 2/5] END ...C=100, gamma=scale, kernel=poly;, score=0.192 total time=   0.0s
[CV 3/5] END ...C=100, gamma=scale, kernel=poly;, score=0.094 total time=   0.0s
[CV 4/5] END ...C=100, gamma=scale, kernel=poly;, score=0.502 total time=   0.0s
[CV 5/5] END ...C=100, gamma=scale, kernel=poly;, score=0.227 total time=   0.0s
[CV 1/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.444 total time=   0.0s
[CV 2/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.668 total time=   0.0s
[CV 3/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.610 total time=   0.0s
[CV 4/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.469 total time=   0.0s
[CV 5/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.329 total time=   0.0s
[CV 1/5] END C=100, gamma=scale, kernel=sigmoid;, score=-2390.671 total time=   0.0s
[CV 2/5] END C=100, gamma=scale, kernel=sigmoid;, score=-2160.021 total time=   0.0s
[CV 3/5] END C=100, gamma=scale, kernel=sigmoid;, score=-1634.156 total time=   0.0s
[CV 4/5] END C=100, gamma=scale, kernel=sigmoid;, score=-1396.558 total time=   0.0s
[CV 5/5] END C=100, gamma=scale, kernel=sigmoid;, score=-1257.939 total time=   0.0s
[CV 1/5] END ..C=100, gamma=auto, kernel=linear;, score=0.505 total time=   0.0s
[CV 2/5] END ..C=100, gamma=auto, kernel=linear;, score=0.665 total time=   0.0s
[CV 3/5] END ..C=100, gamma=auto, kernel=linear;, score=0.514 total time=   0.0s
[CV 4/5] END ..C=100, gamma=auto, kernel=linear;, score=0.581 total time=   0.0s
[CV 5/5] END ..C=100, gamma=auto, kernel=linear;, score=0.263 total time=   0.0s
[CV 1/5] END ....C=100, gamma=auto, kernel=poly;, score=0.061 total time=   0.1s
[CV 2/5] END ...C=100, gamma=auto, kernel=poly;, score=-1.186 total time=   0.1s
[CV 3/5] END ....C=100, gamma=auto, kernel=poly;, score=0.139 total time=   0.1s
[CV 4/5] END ....C=100, gamma=auto, kernel=poly;, score=0.422 total time=   0.1s
[CV 5/5] END ....C=100, gamma=auto, kernel=poly;, score=0.103 total time=   0.1s
[CV 1/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.426 total time=   0.0s
[CV 2/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.692 total time=   0.0s
[CV 3/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.603 total time=   0.0s
[CV 4/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.293 total time=   0.0s
[CV 5/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.381 total time=   0.0s
[CV 1/5] END C=100, gamma=auto, kernel=sigmoid;, score=-2490.472 total time=   0.0s
[CV 2/5] END C=100, gamma=auto, kernel=sigmoid;, score=-1851.564 total time=   0.0s
[CV 3/5] END C=100, gamma=auto, kernel=sigmoid;, score=-1434.722 total time=   0.0s
[CV 4/5] END C=100, gamma=auto, kernel=sigmoid;, score=-1591.289 total time=   0.0s
[CV 5/5] END C=100, gamma=auto, kernel=sigmoid;, score=-2094.271 total time=   0.0s

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=3)

In [54]:
print('Best Parameters :', grid_search.best_params_)
print('Best Score :', grid_search.best_score_)

Best Parameters : {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}
Best Score : 0.5053770439370198

In [56]:
grid_prediction = grid_search.predict(X_test)
grid_prediction

array([17.34767775, 13.21903573, 19.55058534, 31.88976857, 14.61688419,
       15.1911252 , 16.54447094, 14.28317599, 17.09443757, 20.74607469,
       16.36976893, 11.95992397, 11.06942812, 15.1911252 ,  8.94339527,
       13.79410028, 24.24730156, 19.26844348, 14.94748102, 31.75749491,
       21.21601597, 21.0490772 , 21.74019229, 11.89690931, 22.91982365,
       13.78469817, 12.3053231 , 24.89092549, 19.55058534, 35.33433457,
       22.68627694, 13.83749144, 21.03261147, 19.41428921, 20.94773419,
       21.87501888, 16.18315104, 30.40063341, 15.00784463, 15.60190204,
       11.26676267, 12.64479472, 14.95193899, 15.18189243, 14.78006035,
        9.12221787, 14.20993994, 17.77231467, 11.04356028])

In [58]:
from sklearn.metrics import r2_score, mean_absolute_error
print(r2_score(y_test,grid_prediction))
print(mean_absolute_error(y_test, grid_prediction))

0.6605355346675547
4.0466545894129